### ISSUE TITLE
Import error: cannot import name 'deepcopy' from 'bonsaitree.copytools'

### ISSUE THREAD

**Issue by hyl317** [23andMe/bonsaitree#4]
Hi, after installing bonsaitree and passing the test successfully, I encoutered the following error when using it:

`Python 3.8.8 (default, Apr 13 2021, 19:58:26) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from bonsaitree import bonsai
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/home/yh362/.local/lib/python3.8/site-packages/bonsaitree-0.1.dev14+g9df551b-py3.8-linux-x86_64.egg/bonsaitree/bonsai.py", line 13, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/home/yh362/.local/lib/python3.8/site-packages/bonsaitree-0.1.dev14+g9df551b-py3.8-linux-x86_64.egg/bonsaitree/pedigree_object.py", line 9, in <module>
ImportError: cannot import name 'deepcopy' from 'bonsaitree.copytools' (/home/yh362/.cache/Python-Eggs/bonsaitree-0.1.dev14+g9df551b-py3.8-linux-x86_64.egg-tmp/bonsaitree/copytools.cpython-38-x86_64-linux-gnu.so)
>>> 
`

I am unsure what caused this. Hope you can provide some hints. Thanks!

**Comment by ejewett-23andme** [comment]
Hi Yilei, many apologies for not seeing this earlier! This issue is now fixed.
